#!/usr/bin/env ruby

require 'set'

require './lib/santa'
require './lib/transmission'

base_directory = ARGV[1]
raise "#{base_directory} does not exist or isn't a directory" \
  unless Dir.exists? base_directory

state_directory = File.join base_directory, '.presents'
transmission_directory = File.join state_directory, 'transmission'
download_directory = base_directory

raise "#{base_directory} doesn't exist" unless Dir.exist? base_directory
Dir.mkdir state_directory unless Dir.exist? state_directory

port = ARGV[0].to_i
raise "Port is too low" unless port > 1024

puts "Presents"
puts "RPC Port: #{port}"
puts "Directory: #{base_directory}"

@transmission = Transmission.new port, transmission_directory, download_directory
@santa = Santa.new 'http://vivid-sword-3891.herokuapp.com/'
@seen_magnets = Set.new

loop do
  @santa.get do |magnets|
    magnets.each do |m|
      puts "--- got #{m.display_name}" unless @seen_magnets.member? m.info_hash
      @seen_magnets << m.info_hash
    end
    magnets.each { |m| @transmission.add m }
  end

  @transmission.get do |magnets|
    puts "--- publishing #{magnets}"
    Santa.publish magnets
  end

  sleep 5
end
