#!/usr/bin/env ruby

require 'set'
require 'trollop'

require './lib/santa'
require './lib/transmission'

opts = Trollop::options do
  banner <<-EOS
Presents lets you share files with your friends. Don't be a miser.

Usage:
\tpresents [options]

EOS

  opt :dir, "Directory to download to", :type => String
  opt :user, "Email of the user", :type => String
  opt :port, "RPC port for transmission", :default => 1225
  opt :server, "Santa server to listen to", :default => "http://vivid-sword-3891.herokuapp.com/"
  opt :pport, "Port to publish torrents to", :default => 9876
end

base_directory = opts[:dir]
Trollop::die :dir, "must exist" unless Dir.exist? base_directory

state_directory = File.join base_directory, '.presents'
Dir.mkdir state_directory unless Dir.exist? state_directory
transmission_directory = File.join state_directory, 'transmission'

port = opts[:port]
Trollop::die :port, "too low" unless port > 1024

puts "Presents"
puts "RPC Port: #{port}"
puts "Directory: #{base_directory}"

@transmission = Transmission.new port, transmission_directory, base_directory
@santa = Santa.new opts[:user], opts[:server]
@seen_magnets = Set.new

poller = Thread.new do
  loop do
    @santa.get do |magnets|
      magnets.each do |m|
        puts "--- got #{m.display_name}" unless @seen_magnets.member? m.info_hash
        @seen_magnets << m.info_hash
      end
      magnets.each { |m| @transmission.add m }
    end

    sleep 5
  end
end

require 'eventmachine'

module Receiver
  def initialize santa, transmission
    @santa = santa
    @transmission = transmission
  end

  def receive_data data
    close_connection

    data.strip!
    recipient = data[0..data.index(',')-1]
    filename = data[data.index(',')+1..-1]

    puts "--- seeding '#{filename}'"
    magnet = @transmission.seed filename
    puts "--- publishing to '#{recipient}' '#{magnet}'"
    @santa.publish recipient, magnet
  end
end

EM.run do 
  EM.start_server "127.0.0.1", opts[:pport], Receiver, @santa, @transmission
end
